version: '3.7'

x-nomad: &x-nomad |
  {
    "server": {
      "enabled": true,
      "bootstrap_expect": 1
    },
    "datacenter": "city",
    "data_dir": "/tmp/nomad/data/",
    "bind_addr": "0.0.0.0",
    "advertise": {
        "http": "nomad:4646",
        "rpc": "nomad:4647",
        "serf": "nomad:4648"
    },
    "enable_debug": true
  }

services:
  db:
    image: postgres:10.5
    volumes:
      - postgres:/var/lib/postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:4
    command: redis-server --daemonize no


  default: &default
    build:
      context: .
      args:
        - APP_NAME=holepunch
    image: holepunch
    environment:
      - DATABASE_URL=postgres@db:5432
      - CONSUL_HOST=consul
      - SEA_HOST=${SEA_HOST}
      - FLASK_APP=${FLASK_APP}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - .:/holepunch
    depends_on:
      - db
      - consul
      - nomad
      - redis
      - mail
      - jobs

  jump:
    image: cypherpunkarmory/sshd:develop
    volumes:
      - ${SSH_KEY}:/home/punch/.ssh/authorized_keys
    command: bash -l -c 'chown punch:punch /home/punch/.ssh/authorized_keys && chmod 600 /home/punch/.ssh/authorized_keys && /usr/sbin/sshd -D'
    ports:
      - "3122:22"

  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  web:
    <<: *default
    command: bash -l -c 'python -m flask run -h 0.0.0.0'
    ports:
      - "5000:5000"
      - "4444:4444"

  jobs-dash:
    <<: *default
    environment:
      - DATABASE_URL=postgres@db:5432
      - RQ_REDIS_URL=redis://redis:6379
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379
    command: bash -l -c 'rq-dashboard -b 0.0.0.0'
    ports:
      - "9181:9181"

  jobs:
    image: holepunch
    volumes:
      - .:/holepunch
    command: bash -l -c 'python -m flask rq worker'
    ports:
      - "4442:4442"
    depends_on:
      - redis

  consul:
    image: consul
    ports:
      - "8500:8500"
    command: agent -data-dir=/consul/data -config-dir=/consul/config -dev -client 0.0.0.0 -log-level=INFO

  nomad:
    image: cypherpunkarmory/local-nomad:develop
    cap_add:
      - SYS_ADMIN
    environment:
      NOMAD_DATA_DIR: /tmp/nomad/data
      NOMAD_RUN_ROOT: 1
      NOMAD_ADDR: http://nomad:4646
      NOMAD_LOCAL_CONFIG: *x-nomad
    ports:
      - "4646:4646"
    volumes:
      - "/tmp:/tmp"
      - "/tmp/nomad/data:/tmp/nomad/data"
      - "./ssh.hcl:/ssh.hcl"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: agent -dev -bind=0.0.0.0 -consul-address=consul:8500 -consul-auto-advertise=0

  fabio:
    image: fabiolb/fabio:1.5.10-go1.11.1
    environment:
      - FABIO_LOG_LEVEL=DEBUG
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
      - FABIO_PROXY_ADDR=:9999;proto=http,:9991;proto=tcp+sni
    links:
      - consul

    ports:
      - "9998:9998" # GUI/management
      - "80:9999" # HTTP exposed
      - "443:9991" # HTTP exposed

volumes:
  postgres:
