version: '3'
services:

  db:
    image: postgres:10.5
    volumes:
      - postgres:/var/lib/postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:4
    command: redis-server --daemonize no

  default: &default
    build:
      context: .
      args:
        - APP_NAME=holepunch
    image: holepunch
    environment:
      - DATABASE_URL=postgres@db:5432
      - CONSUL_HOST=consul
      - SEA_HOST=nomad
      - FLASK_APP=app:create_app('development')
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - .:/holepunch
    depends_on:
      - db
      - consul
      - nomad
      - redis
      - mail
      - jobs

  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  web:
    <<: *default
    command: bash -l -c 'python -m flask run -h 0.0.0.0'
    ports:
      - "5000:5000"
      - "4444:4444"

  jobs-dash:
    <<: *default
    environment:
      - DATABASE_URL=postgres@db:5432
      - RQ_REDIS_URL=redis://redis:6379
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379
    command: bash -l -c 'rq-dashboard -b 0.0.0.0'
    ports:
      - "9181:9181"

  jobs:
    image: holepunch
    volumes:
      - .:/holepunch
    command: bash -l -c 'python -m flask rq worker'
    ports:
      - "4442:4442"
    depends_on:
      - redis

  consul:
    image: consul
    ports:
      - "8500:8500"
    command: agent -data-dir=/consul/data -config-dir=/consul/config -dev -client 0.0.0.0 -log-level=INFO

  nomad:
    image: stephenprater/populated-nomad
    cap_add:
      - SYS_ADMIN
    environment:
      - NOMAD_DATA_DIR=/tmp/nomad/data
      - NOMAD_RUN_ROOT=1
      - NOMAD_ADDR=http://nomad:4646
    ports:
      - "4646:4646"
    volumes:
      - "/tmp:/tmp"
      - "/tmp/nomad/data:/tmp/nomad/data"
      - "./ssh.hcl:/ssh.hcl"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: agent -dev -bind=0.0.0.0 -consul-address=consul:8500 -consul-auto-advertise=0

  fabio:
    image: fabiolb/fabio:1.5.10-go1.11.1
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
      - FABIO_PROXY_ADDR=:3000;proto=http,:2200;proto=tcp,:2201;proto=tcp,:2202;proto=tcp,:2203;proto=tcp,:2204;proto=tcp,:2205;proto=tcp
    links:
      - consul

    ports:
      - "9998:9998" # GUI/management
      - "9999:9999" # HTTP exposed
      - "2201:2201"
      - "2202:2202"
      - "2203:2203"
      - "2204:2204"
      - "2205:2205"

volumes:
  postgres:
