"""ensure inUse is not null

Revision ID: 083b261e3b0b
Revises: bf5251abcaa2
Create Date: 2019-01-14 18:27:53.739268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "083b261e3b0b"
down_revision = "bf5251abcaa2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("subdomain", "in_use", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("subdomain", "in_use", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
