"""Add Plan Model to DB

Revision ID: 1e1c9c5d8e58
Revises: 7d344f2b41a9
Create Date: 2019-06-05 21:47:53.653018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1e1c9c5d8e58"
down_revision = "7d344f2b41a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tunnel_count", sa.Integer(), nullable=True),
        sa.Column("bandwidth", sa.Integer(), nullable=True),
        sa.Column("forwards", sa.Integer(), nullable=True),
        sa.Column("reserved_subdomains", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("stripe_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plan_name"), "plan", ["name"], unique=True)
    op.create_index(op.f("ix_plan_stripe_id"), "plan", ["stripe_id"], unique=True)
    op.add_column("user", sa.Column("plan_id", sa.Integer(), nullable=True))
    op.alter_column(
        "user",
        "confirmed",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.create_foreign_key("user_plan_fk", "user", "plan", ["plan_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_plan_fk", "user", type_="foreignkey")
    op.alter_column(
        "user",
        "confirmed",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.drop_column("user", "plan_id")
    op.drop_index(op.f("ix_plan_stripe_id"), table_name="plan")
    op.drop_index(op.f("ix_plan_name"), table_name="plan")
    op.drop_table("plan")
    # ### end Alembic commands ###
