"""Add stripe fields to user

Revision ID: 25853ecf738c
Revises: 8813ddff05a2
Create Date: 2019-06-25 17:36:46.573696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "25853ecf738c"
down_revision = "8813ddff05a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("stripe_id", sa.String(length=32), nullable=True))
    op.add_column(
        "user", sa.Column("stripe_payment_method", sa.String(length=32), nullable=True)
    )
    op.create_index(op.f("ix_user_stripe_id"), "user", ["stripe_id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_stripe_id"), table_name="user")
    op.drop_column("user", "stripe_payment_method")
    op.drop_column("user", "stripe_id")
    # ### end Alembic commands ###
