"""change tunnel column names

Revision ID: aaea9ed1df44
Revises: e36675142335
Create Date: 2018-12-13 08:29:03.313823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aaea9ed1df44"
down_revision = "e36675142335"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("subdomain", "in_use", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("subdomain", "reserved", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_constraint("subdomain_name_key", "subdomain", type_="unique")
    op.add_column("tunnel", sa.Column("job_id", sa.String(length=64), nullable=True))
    op.add_column("tunnel", sa.Column("ssh_port", sa.Integer(), nullable=True))
    op.alter_column(
        "tunnel", "port", existing_type=sa.VARCHAR(length=16), nullable=True
    )
    op.alter_column("tunnel", "subdomain_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("tunnel", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_index("ix_tunnel_id", table_name="tunnel")
    op.drop_constraint("tunnel_subdomain_id_key", "tunnel", type_="unique")
    op.drop_column("tunnel", "tunnel_connection_port")
    op.drop_column("tunnel", "tunnel_ssh_port")
    op.drop_column("tunnel", "tunnel_server")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tunnel",
        sa.Column(
            "tunnel_server", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "tunnel",
        sa.Column("tunnel_ssh_port", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "tunnel",
        sa.Column(
            "tunnel_connection_port", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_unique_constraint("tunnel_subdomain_id_key", "tunnel", ["subdomain_id"])
    op.create_index("ix_tunnel_id", "tunnel", ["id"], unique=True)
    op.alter_column("tunnel", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "tunnel", "subdomain_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "tunnel", "port", existing_type=sa.VARCHAR(length=16), nullable=False
    )
    op.drop_column("tunnel", "ssh_port")
    op.drop_column("tunnel", "job_id")
    op.create_unique_constraint("subdomain_name_key", "subdomain", ["name"])
    op.alter_column("subdomain", "reserved", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("subdomain", "in_use", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###
